"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { CssBaseline, Stack, ThemeProvider } from "@mui/material";
import { theme } from "@/theme";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { PropsWithChildren } from "react";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { DataProvider } from "@/components/providers/DataProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AuthProvider>
              <DataProvider>
                <Header />
                <Stack marginTop={"57px"}>{children}</Stack>
                <Footer />
              </DataProvider>
            </AuthProvider>
          </ThemeProvider>
          <CssBaseline />
          <ToastContainer />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
